### ISSUE TITLE
Plugin breaks markup if HTML uses <col> 

### ISSUE THREAD

**Issue by MaXL-ru** [mkoryak/floatThead#261]
Hi.

I have the next makrup:
```html
<table>
  <col class="column1">
  <col class="column2">
  <col class="column3">
  <thead>
    <tr>
      <th>Column 1</th>
      <th>Column 2</th>
      <th>Column 3</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>value 1</td>
      <td>value 2</td>
      <td>value 3</td>
    </tr>
  </tbody>
</table>
```
For <col> CSS classes defined width in percent, like this:
```css
.column1 { width: 20%; }
.column2 { width: 30%; }
.column3 { width: 50%; }
```
After applying plugin:
```javascript
$('table').floatThead();
```
all <col>`s replaces by a new one, with fixed width.

What can I do with this ?
