### ISSUE TITLE
6px gap when using DataTables with Bootstrap 3

### ISSUE THREAD

**Issue by haxney** [mkoryak/floatThead#35]
I am using floatThead with DataTables and Bootstrap 3 and am finding that there is a 6px gap between the top of the floating header and the top of the viewport. See the attached picture:

![screenshot from 2014-01-24 00 43 27](https://f.cloud.github.com/assets/88132/1992363/b7f7e7bc-84ba-11e3-9515-f5f9bf6238a6.png)

I am calling `dataTable` and `floatThead` like so:

``` coffeescript
jQuery ->
  $('.results_round').dataTable
    bPaginate: false
    bInfo: false
    sDom: 't'
    aoColumnDefs: [
      aTargets: ['recalled_header', 'adjudicator_header']
      bSearchable: false
    ]

  $('.results_round').floatThead()
```

And I have the following (S)CSS:

``` scss
thead {
  background-color: red;
}

table.results_round {
  td {
    white-space: nowrap;
  }

  td.mark_cell, td.result_cell {
    width: 1em;
    text-align: center;
    i.fa-heart {
      color: #1D9D74;
    }
  }
}

table.floatThead-table {
    border-top: none;
    border-bottom: none;
    background-color: #FFF;
}
```

(I made the `thead` red to show the issue).

You can see the text poking through the top of the header. The issue seems to be the presence of

``` css
table.dataTable {
  margin-top: 6px !important;
}
```

In `jquery.dataTables.bootstrap3` which I am using from the [jquery-datatables-rails](https://github.com/rweng/jquery-datatables-rails) gem. If I manually disable that rule in FireBug, the gap goes away, but there doesn't seem to be a way to override the `!important` directive. Is there anything which floatThead can do about this?
