### ISSUE TITLE
 The width of thead tr th and tbody tr td not be matched when scroll horizontal and thead overlap the vertical scrollbar 

### ISSUE THREAD

**Issue by nghingothanhnghi** [mkoryak/floatThead#374]
Helo,
I also have a issues. The width of thead tr th and tbody tr td not be matched when scroll horizontal and thead overlap the vertical scrollbar. How to fix its
It's the real on production
![23242424234](https://user-images.githubusercontent.com/10103916/27679561-4d33f8da-5ce3-11e7-8089-97148440ca4b.png)

https://jsfiddle.net/nghingo/1eze7njf/8/

@mkoryak

**Comment by nghingothanhnghi** [comment]
this table using data Table

**Comment by mkoryak** [comment]
modifying styles applied by the plugin with `!important` styles is a good way to break the plugin it turns out :)

this seems to work better:
https://jsfiddle.net/1eze7njf/10/

don't do this: 

```css
.floatThead-container.floated{ }/* add active when scroll*/
.floatThead-container{ width: 100% !important/* scroll inside, not using scroll window*/;border-bottom: 1px solid #ddd; z-index:3 !important /* ovelap when loading*/ }
.floatThead-container table{ table-layout:fixed !important}
```

you shouldnt need to do this, what are you trying to accomplish?
